### ISSUE TITLE
More launch options than just binary

### ISSUE THREAD

**Issue by reynish** [apexskier/nova-jest#173]
I'm working with ECMAScript Modules so I need some extra options around launching Jest

> Execute node with --experimental-vm-modules, e.g. `node --experimental-vm-modules node_modules/.bin/jest` or `NODE_OPTIONS=--experimental-vm-modules npx jest` etc.. On Windows, you can use cross-env to be able to set environment variables.

[https://jestjs.io/docs/ecmascript-modules](https://jestjs.io/docs/ecmascript-modules)

**Comment by biati-digital** [comment]
+1 fo this, the extension does not work once we changed require to import, the tests work correctly running `NODE_OPTIONS=--experimental-vm-modules npx jest` but in this extension no longer works.

**Comment by bdruth** [comment]
Hacky workaround - create a file in your workspace, e.g. `yarn.test` with contents like

```
#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

pushd "${SCRIPT_DIR}"
yarn test "$@"
popd
```

and set the 'Jest executable' to `./yarn.test` ... now it should work as it would when running `yarn test` (or npx or whatever) manually.

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
