### ISSUE TITLE
Feature Request: Configurable working directory

### ISSUE THREAD

**Issue by ticky** [apexskier/nova-jest#29]
Hi there, I’m sorry to not use the existing template, but this isn’t _quite_ a bug, just an issue with our particular, unusual, repo layout!

We have a Rails project which for historical reasons currently has all JavaScript-related stuff inside a `frontend` subdirectory. We’re planning to change that eventually, but for now, it means that this plugin can’t run Jest here, as the Jest configuration, node modules and such live within a subdirectory of the Nova project.

Being able to tell the Jest plugin, for this project, that it should run Jest from within that subdirectory would fix this for us, right now we would just need Jest running inside `/Users/ticky/Repositories/[project]/frontend`.

I’ve not had a chance to look into the code as I’m quite busy this week, but if you’d prefer (and/or don’t get to it first) I can look into opening a PR for this.

Nova version 1.2
nova-jest version 1.1.2

Thanks!

**Comment by apexskier** [comment]
> Hi there, I’m sorry to not use the existing template, but this isn’t _quite_ a bug, just an issue with our particular, unusual, repo layout!

My bad for forgetting to set up my feature request template, that's fixed now.

> Being able to tell the Jest plugin, for this project, that it should run Jest from within that subdirectory would fix this for us, right now we would just need Jest running inside `/Users/ticky/Repositories/[project]/frontend`.

Just to confirm, this is different than setting a custom path to the jest executable? (It's not well documented, but you can [point the plugin to a specific file to execute](https://github.com/apexskier/nova-jest/blob/eb86f63d7d8ea4a1e7eddf720e148047eeb3c461/jest.novaextension/extension.json#L23)).

Adding a configuration to support this should be pretty easy.

**Comment by apexskier** [comment]
Just published a new version with support for this in workspace preferences. Let me know how it goes.

**Comment by ticky** [comment]
> Just to confirm, this is different than setting a custom path to the jest executable?

Yep! Since jest looks in the working directory (currently the workspace's) and directories _above_ that for configuration, it won’t see the configuration we have, unless we can override the working directory!

> Just published a new version with support for this in workspace preferences.

Taking a peek at #30, it looks solid to me! I’ll hopefully get to test it out tomorrow. 😃
