### ISSUE TITLE
Add option to run tests only for changed files

### ISSUE THREAD

**Issue by alex-ketch** [apexskier/nova-jest#39]
Currently this extension runs all tests in the project. For faster performance I'd like to only run tests for changed files by passing the `--onlyChanged` flag.

https://github.com/apexskier/nova-jest/blob/69b7bf6c9c81e025ddee8303f4eb4558699a5dcd/src/main.ts#L83

If this sounds like a reasonable feature I can try to make a PR sometime over the weekend.

**Comment by apexskier** [comment]
The main problem with `--onlyChanged` is this qualifier:

> Only works if you're running tests in a git/hg repository at the moment and requires a static dependency graph (ie. no dynamic requires).

But, if it's an opt-in thing (not default), it seems safe and I'd take a PR.

If you work on this, it should be a simple matter of switching `--watchAll` to `--watch`, which uses `--onlyChanged` by default.
