### ISSUE TITLE
Removing or upgrading Jest shows large error dialog

### ISSUE THREAD

**Issue by jacobbuck** [apexskier/nova-jest#65]
When removing or upgrading the Jest dependency in a project, I get presented with a large error dialog full of stack traces.

**To reproduce**

1. Open a project with Jest installed as a dev-dependency
2. Remove the node_modules directory
3. See error

**Expected behavior**

Either a smaller dialog with only "Jest stopped unexpectedly", or no dialog is shown and Jest is quietly stopped.

**Screenshots**

<img width="266" alt="Screen Shot 2020-11-21 at 12 28 272" src="https://user-images.githubusercontent.com/830470/99864763-0f204400-2c0a-11eb-9eed-dab5e6be01fd.png">

**Environment**

- Nova version: 3 (218855)
- Extension version: 1.3.1
- Sidebar information: Status Running, Jest Version 26.6.3
- macOS version: 11.0.1 (20B29)
- NodeJS information:
  - node version: v15.2.0
  - npm version: 6.14.8
  - installation method: homebrew

**Extension console output**

Jest[14:44:18.536000] node:internal/modules/cjs/loader:922

Jest[14:44:18.544000] throw err;

Jest[14:44:18.558000] ^

Jest[14:44:18.730000] 

Jest[14:44:18.733000] Error: Cannot find module '##REDACTED##/node_modules/jest-worker/build/workers/processChild.js'

Jest[14:44:18.735000] at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)

Jest[14:44:18.736000] at Function.Module._load (node:internal/modules/cjs/loader:763:27)

Jest[14:44:18.737000] at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)

Jest[14:44:18.739000] at node:internal/main/run_main_module:17:47 {

Jest[14:44:18.740000] code: 'MODULE_NOT_FOUND',

Jest[14:44:18.741000] requireStack: []

Jest[14:44:18.741000] }

Jest[14:44:18.743000] node:internal/modules/cjs/loader:922

Jest[14:44:18.744000] throw err;

Jest[14:44:18.744000] ^

Jest[14:44:18.745000] 

Jest[14:44:18.745000] Error: Cannot find module '##REDACTED##/node_modules/jest-worker/build/workers/processChild.js'

Jest[14:44:18.746000] at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)

Jest[14:44:18.748000] at Function.Module._load (node:internal/modules/cjs/loader:763:27)

Jest[14:44:18.750000] at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)

Jest[14:44:18.750000] at node:internal/main/run_main_module:17:47 {

Jest[14:44:18.751000] code: 'MODULE_NOT_FOUND',

Jest[14:44:18.751000] requireStack: []

Jest[14:44:18.752000] }

Jest[14:44:18.754000] node:internal/modules/cjs/loader:922

Jest[14:44:18.754000] throw err;

Jest[14:44:18.755000] ^

Jest[14:44:18.756000] 

Jest[14:44:18.756000] Error: Cannot find module '##REDACTED##/node_modules/jest-worker/build/workers/processChild.js'

Jest[14:44:18.757000] at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)

Jest[14:44:18.757000] at Function.Module._load (node:internal/modules/cjs/loader:763:27)

Jest[14:44:18.758000] at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)

Jest[14:44:18.758000] at node:internal/main/run_main_module:17:47 {

Jest[14:44:18.759000] code: 'MODULE_NOT_FOUND',

Jest[14:44:18.760000] requireStack: []

Jest[14:44:18.760000] }

Jest[14:44:18.860000] node:internal/modules/cjs/loader:922

Jest[14:44:18.863000] throw err;

Jest[14:44:18.866000] ^

Jest[14:44:18.869000] 

Jest[14:44:18.873000] Error: Cannot find module '##REDACTED##/node_modules/jest-worker/build/workers/processChild.js'

Jest[14:44:18.938000] at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)

Jest[14:44:18.939000] at Function.Module._load (node:internal/modules/cjs/loader:763:27)

Jest[14:44:18.941000] at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)

Jest[14:44:18.963000] at node:internal/main/run_main_module:17:47 {

Jest[14:44:18.972000] code: 'MODULE_NOT_FOUND',

Jest[14:44:18.978000] requireStack: []

Jest[14:44:18.981000] }

Jest[14:44:18.981000] node:internal/modules/cjs/loader:922

Jest[14:44:18.982000] throw err;

Jest[14:44:18.982000] ^

Jest[14:44:18.983000] 

Jest[14:44:18.983000] Error: Cannot find module '##REDACTED##/node_modules/jest-worker/build/workers/processChild.js'

Jest[14:44:18.984000] at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)

Jest[14:44:18.985000] at Function.Module._load (node:internal/modules/cjs/loader:763:27)

Jest[14:44:18.985000] at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)

Jest[14:44:18.985000] at node:internal/main/run_main_module:17:47 {

Jest[14:44:18.986000] code: 'MODULE_NOT_FOUND',

Jest[14:44:18.986000] requireStack: []

Jest[14:44:18.987000] }

Jest[14:44:19.159000] node:internal/modules/cjs/loader:922

Jest[14:44:19.162000] throw err;

Jest[14:44:19.166000] ^

Jest[14:44:19.169000] 

Jest[14:44:19.171000] Error: Cannot find module '##REDACTED##/node_modules/jest-worker/build/workers/processChild.js'

Jest[14:44:19.173000] at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)

Jest[14:44:19.173000] at Function.Module._load (node:internal/modules/cjs/loader:763:27)

Jest[14:44:19.174000] at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)

Jest[14:44:19.175000] at node:internal/main/run_main_module:17:47 {

Jest[14:44:19.176000] code: 'MODULE_NOT_FOUND',

Jest[14:44:19.177000] requireStack: []

Jest[14:44:19.179000] }

Jest[14:44:19.180000] node:internal/modules/cjs/loader:922

Jest[14:44:19.181000] throw err;

Jest[14:44:19.182000] ^

Jest[14:44:19.184000] 

Jest[14:44:19.185000] Error: Cannot find module '##REDACTED##/node_modules/jest-worker/build/workers/processChild.js'

Jest[14:44:19.186000] at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)

Jest[14:44:19.186000] at Function.Module._load (node:internal/modules/cjs/loader:763:27)

Jest[14:44:19.187000] at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)

Jest[14:44:19.187000] at node:internal/main/run_main_module:17:47 {

Jest[14:44:19.188000] code: 'MODULE_NOT_FOUND',

Jest[14:44:19.188000] requireStack: []

Jest[14:44:19.189000] }

Jest[14:44:19.228000] node:internal/modules/cjs/loader:922

Jest[14:44:19.228000] throw err;

Jest[14:44:19.229000] ^

Jest[14:44:19.229000] 

Jest[14:44:19.230000] Error: Cannot find module '##REDACTED##/node_modules/jest-worker/build/workers/processChild.js'

Jest[14:44:19.230000] at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)

Jest[14:44:19.231000] at Function.Module._load (node:internal/modules/cjs/loader:763:27)

Jest[14:44:19.231000] at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)

Jest[14:44:19.232000] at node:internal/main/run_main_module:17:47 {

Jest[14:44:19.233000] code: 'MODULE_NOT_FOUND',

Jest[14:44:19.233000] requireStack: []

Jest[14:44:19.234000] }

Jest[14:44:19.246000] node:events:306

Jest[14:44:19.246000] throw er; // Unhandled 'error' event

Jest[14:44:19.247000] ^

Jest[14:44:19.248000] 

Jest[14:44:19.249000] Error: write EPIPE

Jest[14:44:19.252000] at ChildProcess.target._send (node:internal/child_process:839:20)

Jest[14:44:19.252000] at ChildProcess.target.send (node:internal/child_process:710:19)

Jest[14:44:19.253000] at ChildProcessWorker.send (##REDACTED##/node_modules/jest-worker/build/workers/ChildProcessWorker.js:299:17)

Jest[14:44:19.253000] at ##REDACTED##/node_modules/jest-worker/build/base/BaseWorkerPool.js:178:14

Jest[14:44:19.254000] at Array.map (<anonymous>)

Jest[14:44:19.254000] at WorkerPool.end (##REDACTED##/node_modules/jest-worker/build/base/BaseWorkerPool.js:177:46)

Jest[14:44:19.255000] at JestWorker.end (##REDACTED##/node_modules/jest-worker/build/index.js:199:29)

Jest[14:44:19.256000] at cleanup (##REDACTED##/node_modules/jest-runner/build/index.js:295:42)

Jest[14:44:19.256000] at processTicksAndRejections (node:internal/process/task_queues:93:5)

Jest[14:44:19.257000] at TestRunner.runTests (##REDACTED##/node_modules/jest-runner/build/index.js:108:12)

Jest[14:44:19.257000] Emitted 'error' event on ChildProcess instance at:

Jest[14:44:19.258000] at node:internal/child_process:843:39

Jest[14:44:19.258000] at processTicksAndRejections (node:internal/process/task_queues:75:11) {

Jest[14:44:19.259000] errno: -32,

Jest[14:44:19.259000] code: 'EPIPE',

Jest[14:44:19.260000] syscall: 'write'

Jest[14:44:19.260000] }

Jest[14:57:18.813000] reloading...

Jest[14:57:19.139000] using jest at: ##REDACTED##/node_modules/.bin/jest

Jest[14:57:19.139000] running in: ##REDACTED##

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
