### ISSUE TITLE
Custom jest config path

### ISSUE THREAD

**Issue by jefflewis** [apexskier/nova-jest#70]
Support for specifying the path to the [jest config](https://jestjs.io/docs/en/configuration.html) would be awesome.

e.g. when running from the command line: `jest --config ./jest/jest.config.js`

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
