### ISSUE TITLE
Ability to view output from jest tests

### ISSUE THREAD

**Issue by austinfox** [apexskier/nova-jest#71]
When I'm fixing an issue with a broken jest test, I usually use various console.log statements to output variable values to help me root cause the issue. Is there currently a way to see this info from the jest extension pane in Nova? If not, is this something that is planned in the future? Thanks for maintaining this awesome extension!

**Comment by bdruth** [comment]
Doing TDD is very difficult without seeing the actual Jest output.

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
